### PR TITLE
Update to 1.18

### PR DESCRIPTION
**Pull request by kosma**
Does what it says on the tin.

### CODE REVIEW

**Comment by smujaddid** [comment]
Have you tested it to run in Minecraft 1.18?

**Comment by smujaddid** [comment]
@kosma Can you check the errors?

**Comment by kosma** [comment]
My bad, didn't realize there's a CI setup. I have tested in-game, here's how it looks:
image

**Comment by smujaddid** [comment]
> My bad, didn't realize there's a CI setup. I have tested in-game, here's how it looks: image

Wow. Thank you. I'll accept this and release it as soon as possible. But, I made a few modifications to the build.gradle. Can you test it again after I push the commits?

**Comment by smujaddid** [comment]
A second thought. I will create new branch for 1.18. Can you re-create this PR or change target branch to 1.18?

**Comment by kosma** [comment]
You should be able to change the target branch yourself as the repository owner :)

**Comment by smujaddid** [comment]
> You should be able to change the target branch yourself as the repository owner :)

You're right! :)

**Pull request merged**
